### ISSUE TITLE
Syned Remote repository not reading

### ISSUE THREAD

**Issue by maltissimo** [lucarebuffi/OASYS-SYNED#2]
Hello, 

I am trying to set up a remote repository of data for Elettra, to be used with Syned. I created a link on our share drive (https://drive.elettra.eu/d/59a4c39fa94d45d0b116/), but if I place it in the Syned File Name/URL box, I get the following error: 

![Screen Shot 2019-05-23 at 11 43 44](https://user-images.githubusercontent.com/41440861/58243057-45001600-7d50-11e9-886d-3d08fe13fec4.png)

I am not too sure whether Syned would read only an ftp, or also from http. What it looks like from the error message is that it's creating the path using Oasys' Working directory. 

Thank you

Matteo

**Comment by srio** [comment]
Hello Matteo, 

two things: 
- The address https://drive.elettra.eu/d/59a4c39fa94d45d0b116/files/?p=/U2_150_E2-S6BAE_002.json does not work because the server places a frame around it. You should use the raw data address (I got it pointing on the "download" link and right-click and select "copy link address" - I use Chrome).
- However this is not enough. You should replace "https" by "http", so remove an "s" in the address. If I do so, it works for me. 

This is a small bug, I keep the issue open until fixing it.

**Comment by maltissimo** [comment]
Thank you Manuel, 

I’ll give it a go and see how it looks like. What I really would like to do is to have a repository somewhere (either ftp or http), and people being able to see and select the file from there. By memory, wasn’t this what you have shown the other week? 

Thank you

Matteo

**Comment by srio** [comment]
Everything works if given the ASCII file address: 
https://drive.elettra.eu/d/59a4c39fa94d45d0b116/files/?p=%2FU10_40_E2-S6BAE_002_LP.json&dl=1
